# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '10.2.0.21:9202' }
    indexes:
        oils_distributor_volume:
            properties:
                target: ~
                quantity: { boost: 10, analyzer: my_analyzer }
                tags:
                price_liter:
            persistence:
                driver: orm
                model: App\Entity\PdmOilsDistributorVolume
                provider: ~
                finder: ~